# Site settings
title: nbookham.net
description: Nathan's personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nbookham.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# SASS
sass:
  style: compressed

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default

# Include
include:
  - _redirects

# Exclude
exclude:
  - assets/js/bootstrap.bundle.min.js
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
